# Site settings
title: Create Online Quizzes That Drive Revenue · Qzzr
email: support@qzzr.com
description: > # this means to ignore newlines until "baseurl:"
  Qzzr is a simple online quiz tool that allows get better leads, improved engagement, and more revenue.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.qzzr.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
